

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    container_name: vector_consumer
    restart: always
    env_file:
      - path: ./.env 